version: '3.8'

services:
  html-app-container:
    build: .
    image: docker-image-containers:v2 
    restart: always
    container_name: html-app-container
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
  

